<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UnifiedSeeder extends Seeder
{
    // Small placeholder base64 images (1x1 transparent PNG)
    private $placeholderImage = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';

    // Base64 for destination image placeholder
    private $destinationPlaceholder = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=';

    // Base64 for profile photo placeholder
    private $profilePlaceholder = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFBQIAX8jx0gAAAABJRU5ErkJggg==';

    // Base64 for partner logo placeholder
    private $logoPlaceholder = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==';

    public function run()
    {
        // Seed in order of dependencies
        $this->seedAdmin();
        $this->seedSettings();
        $this->seedDestinations();
        $this->seedTestimonials();
        $this->seedTeamMembers();
        $this->seedPartners();

        echo "Database seeding completed successfully!\n";
    }

    private function seedAdmin()
    {
        $data = [
            [
                'username' => 'admin',
                'password' => password_hash('admin123', PASSWORD_DEFAULT),
                'email' => 'admin@traveltrust.com',
                'full_name' => 'Administrator',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('users')->insertBatch($data);
        echo "Admin user seeded successfully (username: admin, password: admin123).\n";
    }

    private function seedSettings()
    {
        $data = [
            [
                'setting_key' => 'site_name',
                'setting_value' => 'TravelTrust',
                'setting_type' => 'text',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'setting_key' => 'site_tagline',
                'setting_value' => 'Your Trusted Travel Partner',
                'setting_type' => 'text',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'setting_key' => 'site_logo',
                'setting_value' => $this->logoPlaceholder,
                'setting_type' => 'image',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'setting_key' => 'contact_email',
                'setting_value' => 'info@traveltrust.com',
                'setting_type' => 'text',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'setting_key' => 'contact_phone',
                'setting_value' => '+977-1-4421234',
                'setting_type' => 'text',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'setting_key' => 'contact_address',
                'setting_value' => 'Thamel, Kathmandu, Nepal',
                'setting_type' => 'text',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'setting_key' => 'hero_title',
                'setting_value' => 'Explore the World with Confidence',
                'setting_type' => 'text',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'setting_key' => 'hero_subtitle',
                'setting_value' => 'Discover Amazing Destinations',
                'setting_type' => 'text',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'setting_key' => 'hero_description',
                'setting_value' => 'TravelTrust offers personalized travel experiences to destinations around the world. Let us help you create unforgettable memories with our expert travel planning services.',
                'setting_type' => 'textarea',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'setting_key' => 'about_content',
                'setting_value' => 'At TravelTrust, we are passionate about creating exceptional travel experiences. With over 15 years of experience in the travel industry, our dedicated team of travel experts works tirelessly to ensure every journey exceeds your expectations. From exotic beach getaways to cultural city tours, we specialize in crafting personalized itineraries that match your unique travel style and preferences.',
                'setting_type' => 'textarea',
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('settings')->insertBatch($data);
        echo "Settings seeded successfully.\n";
    }

    private function seedDestinations()
    {
        $data = [
            // Europe
            [
                'name' => 'Paris',
                'country' => 'France',
                'description' => 'The City of Light offers iconic landmarks, world-class museums, and romantic ambiance.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'landmark',
                'is_featured' => 1,
                'display_order' => 1,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Rome',
                'country' => 'Italy',
                'description' => 'Ancient history meets modern culture in this eternal city of art, architecture, and cuisine.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'church',
                'is_featured' => 1,
                'display_order' => 2,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Barcelona',
                'country' => 'Spain',
                'description' => 'Gaudi\'s architectural masterpieces, Mediterranean beaches, and vibrant nightlife.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'building',
                'is_featured' => 1,
                'display_order' => 3,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Amsterdam',
                'country' => 'Netherlands',
                'description' => 'Picturesque canals, world-class museums, and historic architecture.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'bicycle',
                'is_featured' => 0,
                'display_order' => 4,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'London',
                'country' => 'United Kingdom',
                'description' => 'Royal palaces, iconic landmarks, and a blend of tradition and modernity.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'crown',
                'is_featured' => 1,
                'display_order' => 5,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Santorini',
                'country' => 'Greece',
                'description' => 'White-washed buildings, blue-domed churches, and breathtaking sunsets over the Aegean Sea.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'sun',
                'is_featured' => 1,
                'display_order' => 6,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Prague',
                'country' => 'Czech Republic',
                'description' => 'Medieval architecture, cobblestone streets, and rich cultural heritage.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'chess-rook',
                'is_featured' => 0,
                'display_order' => 7,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Vienna',
                'country' => 'Austria',
                'description' => 'Imperial palaces, classical music heritage, and elegant coffee houses.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'music',
                'is_featured' => 0,
                'display_order' => 8,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Reykjavik',
                'country' => 'Iceland',
                'description' => 'Gateway to natural wonders including geysers, waterfalls, and Northern Lights.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'snowflake',
                'is_featured' => 0,
                'display_order' => 9,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Lisbon',
                'country' => 'Portugal',
                'description' => 'Colorful tiles, historic trams, and stunning coastal views.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'ship',
                'is_featured' => 0,
                'display_order' => 10,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Asia
            [
                'name' => 'Tokyo',
                'country' => 'Japan',
                'description' => 'Experience the perfect blend of ancient traditions and cutting-edge technology.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'torii-gate',
                'is_featured' => 1,
                'display_order' => 11,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bali',
                'country' => 'Indonesia',
                'description' => 'Tropical paradise with beautiful beaches, lush rice terraces, and spiritual temples.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'umbrella-beach',
                'is_featured' => 1,
                'display_order' => 12,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bangkok',
                'country' => 'Thailand',
                'description' => 'Vibrant street life, ornate temples, and world-renowned cuisine.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'temple',
                'is_featured' => 1,
                'display_order' => 13,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Singapore',
                'country' => 'Singapore',
                'description' => 'Modern city-state with futuristic architecture and diverse culinary scene.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'building',
                'is_featured' => 0,
                'display_order' => 14,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Hong Kong',
                'country' => 'China',
                'description' => 'Dynamic metropolis with stunning skyline, harbor views, and rich cultural mix.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'city',
                'is_featured' => 0,
                'display_order' => 15,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Seoul',
                'country' => 'South Korea',
                'description' => 'Modern K-pop culture meets ancient palaces and traditional markets.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'landmark',
                'is_featured' => 0,
                'display_order' => 16,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kyoto',
                'country' => 'Japan',
                'description' => 'Ancient capital with thousands of temples, traditional tea houses, and zen gardens.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'torii-gate',
                'is_featured' => 1,
                'display_order' => 17,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Maldives',
                'country' => 'Maldives',
                'description' => 'Paradise islands with crystal-clear waters, luxury resorts, and pristine beaches.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'water',
                'is_featured' => 1,
                'display_order' => 18,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kathmandu',
                'country' => 'Nepal',
                'description' => 'Gateway to the Himalayas with ancient temples and rich spiritual heritage.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'mountain',
                'is_featured' => 0,
                'display_order' => 19,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dubai',
                'country' => 'UAE',
                'description' => 'Modern luxury meets Arabian heritage in this desert metropolis.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'mosque',
                'is_featured' => 1,
                'display_order' => 20,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Americas
            [
                'name' => 'New York',
                'country' => 'USA',
                'description' => 'The city that never sleeps, offering endless entertainment and cultural experiences.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'building',
                'is_featured' => 1,
                'display_order' => 21,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Los Angeles',
                'country' => 'USA',
                'description' => 'Home to Hollywood, beautiful beaches, and year-round sunshine.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'film',
                'is_featured' => 0,
                'display_order' => 22,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Rio de Janeiro',
                'country' => 'Brazil',
                'description' => 'Carnival, Christ the Redeemer, and stunning beaches like Copacabana.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'umbrella-beach',
                'is_featured' => 1,
                'display_order' => 23,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Buenos Aires',
                'country' => 'Argentina',
                'description' => 'Tango, steakhouses, and European-style architecture in South America.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'music',
                'is_featured' => 0,
                'display_order' => 24,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Cancun',
                'country' => 'Mexico',
                'description' => 'Caribbean beaches, Mayan ruins, and world-class resorts.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'sun',
                'is_featured' => 1,
                'display_order' => 25,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Vancouver',
                'country' => 'Canada',
                'description' => 'Mountains meet ocean in this beautiful coastal city.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'mountain',
                'is_featured' => 0,
                'display_order' => 26,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Toronto',
                'country' => 'Canada',
                'description' => 'Multicultural metropolis with CN Tower and vibrant neighborhoods.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'city',
                'is_featured' => 0,
                'display_order' => 27,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Las Vegas',
                'country' => 'USA',
                'description' => 'Entertainment capital with world-famous casinos and spectacular shows.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'dice',
                'is_featured' => 0,
                'display_order' => 28,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'San Francisco',
                'country' => 'USA',
                'description' => 'Golden Gate Bridge, cable cars, and innovative tech culture.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'bridge',
                'is_featured' => 0,
                'display_order' => 29,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Miami',
                'country' => 'USA',
                'description' => 'Art deco architecture, Latin culture, and beautiful beaches.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'palm-tree',
                'is_featured' => 0,
                'display_order' => 30,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Africa & Middle East
            [
                'name' => 'Cape Town',
                'country' => 'South Africa',
                'description' => 'Table Mountain, stunning coastline, and diverse wildlife.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'mountain',
                'is_featured' => 1,
                'display_order' => 31,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Marrakech',
                'country' => 'Morocco',
                'description' => 'Vibrant souks, stunning riads, and Sahara Desert adventures.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'landmark',
                'is_featured' => 1,
                'display_order' => 32,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Cairo',
                'country' => 'Egypt',
                'description' => 'Ancient pyramids, Sphinx, and timeless Nile River cruises.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'monument',
                'is_featured' => 1,
                'display_order' => 33,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Istanbul',
                'country' => 'Turkey',
                'description' => 'Where East meets West, with historic mosques and bustling bazaars.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'mosque',
                'is_featured' => 1,
                'display_order' => 34,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Jerusalem',
                'country' => 'Israel',
                'description' => 'Sacred city with profound historical and religious significance.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'place-of-worship',
                'is_featured' => 0,
                'display_order' => 35,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Oceania
            [
                'name' => 'Sydney',
                'country' => 'Australia',
                'description' => 'Iconic Opera House, harbor bridge, and beautiful beaches.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'water',
                'is_featured' => 1,
                'display_order' => 36,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Melbourne',
                'country' => 'Australia',
                'description' => 'Coffee culture, street art, and world-class dining scene.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'coffee',
                'is_featured' => 0,
                'display_order' => 37,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Auckland',
                'country' => 'New Zealand',
                'description' => 'City of sails with volcanic landscapes and Maori culture.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'sailboat',
                'is_featured' => 0,
                'display_order' => 38,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Queenstown',
                'country' => 'New Zealand',
                'description' => 'Adventure capital with stunning alpine scenery and outdoor activities.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'mountain',
                'is_featured' => 1,
                'display_order' => 39,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Fiji',
                'country' => 'Fiji',
                'description' => 'Tropical paradise with pristine waters and warm island hospitality.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'island-tropical',
                'is_featured' => 1,
                'display_order' => 40,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            // Additional Popular Destinations
            [
                'name' => 'Phuket',
                'country' => 'Thailand',
                'description' => 'Thailand\'s largest island with stunning beaches and vibrant nightlife.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'umbrella-beach',
                'is_featured' => 0,
                'display_order' => 41,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Edinburgh',
                'country' => 'Scotland',
                'description' => 'Historic castle, festivals, and Scottish highlands gateway.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'chess-rook',
                'is_featured' => 0,
                'display_order' => 42,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Venice',
                'country' => 'Italy',
                'description' => 'Floating city of canals, gondolas, and Renaissance art.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'water',
                'is_featured' => 1,
                'display_order' => 43,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Machu Picchu',
                'country' => 'Peru',
                'description' => 'Ancient Incan citadel high in the Andes Mountains.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'mountain',
                'is_featured' => 1,
                'display_order' => 44,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Petra',
                'country' => 'Jordan',
                'description' => 'Ancient archaeological city carved into rose-red cliffs.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'landmark',
                'is_featured' => 0,
                'display_order' => 45,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bora Bora',
                'country' => 'French Polynesia',
                'description' => 'Ultimate luxury destination with overwater bungalows and turquoise lagoons.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'umbrella-beach',
                'is_featured' => 1,
                'display_order' => 46,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dubrovnik',
                'country' => 'Croatia',
                'description' => 'Pearl of the Adriatic with medieval walls and Game of Thrones fame.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'fort-awesome',
                'is_featured' => 0,
                'display_order' => 47,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Seychelles',
                'country' => 'Seychelles',
                'description' => 'Pristine beaches, granite boulders, and exclusive island resorts.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'island-tropical',
                'is_featured' => 1,
                'display_order' => 48,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bagan',
                'country' => 'Myanmar',
                'description' => 'Ancient city with thousands of Buddhist temples and pagodas.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'gopuram',
                'is_featured' => 0,
                'display_order' => 49,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Havana',
                'country' => 'Cuba',
                'description' => 'Colorful colonial architecture, vintage cars, and vibrant music scene.',
                'image_url' => $this->destinationPlaceholder,
                'icon' => 'car',
                'is_featured' => 0,
                'display_order' => 50,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('destinations')->insertBatch($data);
        echo "50 destinations seeded successfully.\n";
    }

    private function seedTestimonials()
    {
        $data = [
            [
                'client_name' => 'Rajesh Kumar Sharma',
                'client_position' => 'Business Owner',
                'client_photo' => $this->profilePlaceholder,
                'testimonial_text' => 'TravelTrust planned our family trip to Bali and it was absolutely amazing! Every detail was perfectly organized, from the airport transfers to the hotel bookings. My kids loved the cultural tours and the beach activities. This was truly a memorable experience for our entire family. Highly recommended!',
                'rating' => 5,
                'destination' => 'Bali',
                'is_featured' => 1,
                'display_order' => 1,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'client_name' => 'Priya Thapa',
                'client_position' => 'Marketing Manager',
                'client_photo' => $this->profilePlaceholder,
                'testimonial_text' => 'I have been using TravelTrust for all my business trips for the past two years. Their attention to detail and 24/7 customer support is exceptional. They always find the best flight options and hotels that meet my needs. Professional, reliable, and always a pleasure to work with!',
                'rating' => 5,
                'destination' => 'Dubai',
                'is_featured' => 1,
                'display_order' => 2,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'client_name' => 'Sanjay Adhikari',
                'client_position' => 'Software Engineer',
                'client_photo' => $this->profilePlaceholder,
                'testimonial_text' => 'My honeymoon in Maldives was a dream come true thanks to TravelTrust. They arranged everything perfectly - from the overwater villa to the romantic candlelight dinners. The team went above and beyond to make our special trip unforgettable. We couldn\'t have asked for a better experience!',
                'rating' => 5,
                'destination' => 'Maldives',
                'is_featured' => 1,
                'display_order' => 3,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('testimonials')->insertBatch($data);
        echo "3 testimonials seeded successfully.\n";
    }

    private function seedTeamMembers()
    {
        $data = [
            [
                'name' => 'Rajendra Prasad Sharma',
                'position' => 'CEO & Founder',
                'bio' => 'With over 15 years of experience in the travel and tourism industry, Rajendra founded TravelTrust to provide exceptional travel experiences. His passion for exploring new cultures and destinations drives the company\'s vision.',
                'photo_url' => $this->profilePlaceholder,
                'email' => 'rajendra@traveltrust.com',
                'phone' => '+977-1-4421234',
                'facebook' => 'https://facebook.com/rajendrasharma',
                'twitter' => 'https://twitter.com/rajendrasharma',
                'linkedin' => 'https://linkedin.com/in/rajendrasharma',
                'display_order' => 1,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sunita Tamang',
                'position' => 'Head of Operations',
                'bio' => 'Sunita ensures every journey runs smoothly with her meticulous planning and organizational skills. Her expertise in luxury travel and customer service excellence has earned the company numerous accolades.',
                'photo_url' => $this->profilePlaceholder,
                'email' => 'sunita@traveltrust.com',
                'phone' => '+977-1-4421235',
                'facebook' => 'https://facebook.com/sunitatamang',
                'twitter' => '',
                'linkedin' => 'https://linkedin.com/in/sunitatamang',
                'display_order' => 2,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bikash Adhikari',
                'position' => 'Senior Travel Consultant',
                'bio' => 'Bikash specializes in adventure tourism and trekking expeditions. Having personally explored the Himalayas and various international destinations, he brings firsthand knowledge to create unforgettable travel experiences.',
                'photo_url' => $this->profilePlaceholder,
                'email' => 'bikash@traveltrust.com',
                'phone' => '+977-1-4421236',
                'facebook' => '',
                'twitter' => 'https://twitter.com/bikashadhikari',
                'linkedin' => 'https://linkedin.com/in/bikashadhikari',
                'display_order' => 3,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Anjali Gurung',
                'position' => 'Customer Relations Manager',
                'bio' => 'Anjali is dedicated to ensuring every client receives personalized attention and exceptional service. Her warm personality and problem-solving skills make her the go-to person for all customer inquiries.',
                'photo_url' => $this->profilePlaceholder,
                'email' => 'anjali@traveltrust.com',
                'phone' => '+977-1-4421237',
                'facebook' => 'https://facebook.com/anjaligurung',
                'twitter' => '',
                'linkedin' => 'https://linkedin.com/in/anjaligurung',
                'display_order' => 4,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ramesh Thapa',
                'position' => 'Tour Package Designer',
                'bio' => 'Ramesh creates customized travel packages that cater to diverse interests and budgets. With his creative approach and extensive knowledge of global destinations, he crafts unique itineraries for memorable journeys.',
                'photo_url' => $this->profilePlaceholder,
                'email' => 'ramesh@traveltrust.com',
                'phone' => '+977-1-4421238',
                'facebook' => '',
                'twitter' => '',
                'linkedin' => 'https://linkedin.com/in/rameshthapa',
                'display_order' => 5,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kopila Rai',
                'position' => 'Marketing & Social Media Manager',
                'bio' => 'Kopila handles all marketing initiatives and maintains the company\'s vibrant social media presence. Her creative campaigns and engaging content have significantly expanded TravelTrust\'s reach and client base.',
                'photo_url' => $this->profilePlaceholder,
                'email' => 'kopila@traveltrust.com',
                'phone' => '+977-1-4421239',
                'facebook' => 'https://facebook.com/kopilarai',
                'twitter' => 'https://twitter.com/kopilarai',
                'linkedin' => 'https://linkedin.com/in/kopilarai',
                'display_order' => 6,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('members')->insertBatch($data);
        echo "6 team members seeded successfully.\n";
    }

    private function seedPartners()
    {
        $data = [
            [
                'name' => 'Emirates Airlines',
                'logo_url' => $this->logoPlaceholder,
                'website' => 'https://www.emirates.com',
                'display_order' => 1,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Qatar Airways',
                'logo_url' => $this->logoPlaceholder,
                'website' => 'https://www.qatarairways.com',
                'display_order' => 2,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Marriott International',
                'logo_url' => $this->logoPlaceholder,
                'website' => 'https://www.marriott.com',
                'display_order' => 3,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Hilton Hotels & Resorts',
                'logo_url' => $this->logoPlaceholder,
                'website' => 'https://www.hilton.com',
                'display_order' => 4,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Singapore Airlines',
                'logo_url' => $this->logoPlaceholder,
                'website' => 'https://www.singaporeair.com',
                'display_order' => 5,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Booking.com',
                'logo_url' => $this->logoPlaceholder,
                'website' => 'https://www.booking.com',
                'display_order' => 6,
                'status' => 'active',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('partners')->insertBatch($data);
        echo "6 partners seeded successfully.\n";
    }
}
